server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/comments/**

        - id: like-service
          uri: lb://LIKE-SERVICE
          predicates:
            - Path=/api/likes/**

        - id: follow-service
          uri: lb://FOLLOW-SERVICE
          predicates:
            - Path=/api/follow/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/media/**

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/search/**

# ✅ JWT FIX
jwt:
  secret: ${JWT_SECRET}

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG