server:
  port: 8086

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://localhost:3306/connectsphere_notification_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

auth:
  service:
    url: http://localhost:8081

post:
  service:
    url: http://localhost:8082

comment:
  service:
    url: http://localhost:8083

like:
  service:
    url: http://localhost:8084

follow:
  service:
    url: http://localhost:8085

logging:
  level:
    com.connectsphere: DEBUG